### ISSUE TITLE
MethodError: no method matching full_bunching_probability(::RandHaar, ::Input{Bosonic}, ::ModeOccupation)

### ISSUE THREAD

**Issue by AntoineRestivo** [AntoineRestivo/BosonSampling.jl#52]
https://github.com/benoitseron/BosonSampling.jl/blob/ecea4cfb898422b02cf37e0ce0a27a78e5ba2e65/src/example_usage.jl#L28

**Comment by AntoineRestivo** [comment]
Do you absolutely need `subset_modes` to be of type `Subset` in here
`function full_bunching_probability(interf::Interferometer, i::Input, subset_modes::Subset)`?

**Comment by benoitseron** [comment]
I am having a look but more bugs seem to appear when I fix some
